NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.carriers.transporter.logistic.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.carriers.transporter.logistic.com-cert.pem
    OrganizationalUnitIdentifier: peer
